### ISSUE TITLE
Request: add ability to convert google docs pages

### ISSUE THREAD

**Issue by angrydestreyer9** [axoletl/not-br-ext#2]
I don't know too much about this, but for class assignments there is usually large amounts of text on a google doc that I don't have permission to edit 

also adding the ability to convert a doc that I own into BR and then back out when I am turning it in would be great

**Comment by axoletl** [comment]
hi! i dont think this is actually possible in the context of a browser extension, the text on googles docs isnt actually normal text, and is black boxed in something called a canvas thats effectively just an image/video. while not ideal, you could try your luck with manually converting it using my other project not-br.neocities.org

**Comment by angrydestreyer9** [comment]
Thank you, I am atually just learning how to code with canvas, I think that there might be a way to edit the text if the extension seeks the canvas and converts what is inside of that, however I can't find it with inspect element, and that seems quite complicated. Maybe I will learn how to code docs extensions and borrow some of your code.

**Comment by axoletl** [comment]
feel free to! google docs addons (unless that's what you meant) might be the way forward for a docs specific solution, but on the browser extension end as there is no way to access canvas content im a bit limited
