### ISSUE TITLE
Request/help: Options or instructions to tweak spacing

### ISSUE THREAD

**Issue by vaultdveller** [axoletl/not-br-ext#3]
I have very basic understanding of js/css so i could not get any adjusted row spacing to work after fiddling with some values
People would probably enjoy some tips on how to customize for different needs like in the online converter
My main challenge is to get bigger row spacing for my little sister to help her studies go easier but even in this state its already much easier to read for her

**Comment by axoletl** [comment]
hi! unless im misunderstanding the line height slider should allow you to tweak the spacing between rows, instructions to make this clearer would be helpful and something i consider down the line though, thanks!

**Comment by vaultdveller** [comment]
I meat that i cant change those spacings in the extension, online converter works fine

**Comment by axoletl** [comment]
![image](https://user-images.githubusercontent.com/38306961/172043991-65625d26-437c-4c1a-b148-1f31ed1bff46.png)
![image](https://user-images.githubusercontent.com/38306961/172043998-a2772b96-90e3-4416-846a-5b2c41e1197e.png)
![image](https://user-images.githubusercontent.com/38306961/172044003-72f72120-ddcc-4345-b779-eba33259d5cc.png)
![image](https://user-images.githubusercontent.com/38306961/172044006-9a9c07f8-03d5-4971-bfe0-eaf745208ef2.png)
it seems to be working on the extension? unless you mean you wanted it to be a larger difference which i can do, or is it not working on a particular site?

**Comment by vaultdveller** [comment]
Sorry for not being more clear
When i right click on a page to convert it it uses default settings
How do i change how the chore extension spaces the lines on e.g wkipedia?
what file and variable do i need to change?

**Comment by axoletl** [comment]
the settings are in a panel that shows up when you click on the extension icon, no need to adjust any files or variables 

> To adjust settings, click the notBR icon to open the extension popup panel from your extension toolbar (may need to be pinned from extensions list, see [here](https://www.howtogeek.com/683099/how-to-pin-and-unpin-extensions-from-the-chrome-toolbar/))

![image](https://user-images.githubusercontent.com/38306961/172057032-2dd06d57-1149-408d-9f79-07894eecf027.png)
![image](https://user-images.githubusercontent.com/38306961/172057041-b43a838d-8093-4999-8dcd-4320695ff9e3.png)


hope this helps?

**Comment by vaultdveller** [comment]
So sorry, didn't notice that you could adjust it from that little button, apologies for wasting time

**Comment by axoletl** [comment]
no worries! ill see if i can make it clearer
